language: python
os: linux
dist: xenial
python:
  - "3.6"

branches:
  only:
  - master

install:
    - pip install flake8==3.7.7
    - pip install mypy==0.700
    - make setup

script:
    - make build